version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      - VITE_API_JAVA=http://localhost:3000/api/java
    depends_on:
      - backend-java
    networks:
      - loyalty-network

  backend-java:
    build:
      context: ./backend-java
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/loyalty
      - SPRING_DATA_MONGODB_DATABASE=loyalty
      - CORS_ALLOWED_ORIGINS=http://localhost:3000
      - JWT_SECRET=c9c1b2f3e4a5d6b7c8a9e0f1d2c3b4a5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1
      - BLOCKCHAIN_API_URL=http://localhost:8081
    depends_on:
      - mongodb
    networks:
      - loyalty-network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - loyalty-network

  ollama:
    image: ollama/ollama:latest
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - loyalty-network
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G
    command: ["serve"]
    healthcheck:
      test: ["CMD-SHELL", "ollama --version > /dev/null 2>&1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  ollama-pull:
    image: ollama/ollama:latest
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - loyalty-network
    environment:
      - OLLAMA_HOST=http://ollama:11434
    command: ["pull", "phi3"]
    depends_on:
      ollama:
        condition: service_healthy

  llm-service:
    build:
      context: ./llm-guard-service
      dockerfile: Dockerfile
    ports:
      - "8082:8000"
    environment:
      - OLLAMA_API_URL=http://ollama:11434
      - OLLAMA_MODEL=phi3
      - HF_HOME=/root/.cache/huggingface
    volumes:
      - llm_cache:/root/.cache/huggingface
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    depends_on:
      ollama:
        condition: service_healthy
      ollama-pull:
        condition: service_completed_successfully
    networks:
      - loyalty-network

networks:
  loyalty-network:
    driver: bridge

volumes:
  mongodb_data:
  ollama_data:
  llm_cache:
