version: '3.8'

services:
  backend-java:
    build: 
      context: ./backend-java
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/loyalty
      - JWT_SECRET=${JAVA_JWT_SECRET}
    depends_on:
      - mongo
    networks:
      - loyalty-network

  backend-go:
    build:
      context: ./backend-go
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - MONGO_URI=mongodb://mongo:27017/loyalty
      - LOG_LEVEL=${GO_LOG_LEVEL}
    depends_on:
      - mongo
    networks:
      - loyalty-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_JAVA_API_URL=http://localhost:8080
      - REACT_APP_GO_API_URL=http://localhost:8081
    depends_on:
      - backend-java
      - backend-go
    networks:
      - loyalty-network

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - loyalty-network

networks:
  loyalty-network:
    driver: bridge

volumes:
  mongodb_data:
