server:
  port: 8080

spring:
  data:
    mongodb:
      host: mongodb
      port: 27017
      database: loyalty
      authentication-database: admin

blockchain:
  service:
    url: http://backend-go:8081

jwt:
  secret: your-secret-key
  expiration: 86400000 # 24 hours

rsa:
  private-key: classpath:keys/private.key
  public-key: classpath:keys/public.key

logging:
  level:
    org.springframework.web: INFO
    com.loyalty: DEBUG
    org.mongodb: INFO