spring:
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/loyalty}
      database: ${SPRING_DATA_MONGODB_DATABASE:loyalty}

jwt:
  secret: ${JWT_SECRET}
  token-validity-in-seconds: 86400

server:
  port: 8080

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000}

blockchain:
  api:
    url: ${BLOCKCHAIN_API_URL:http://backend-go:8081}